# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The HolidayCheck Tech Blog
email: ????@holidaycheck.com
description: > # this means to ignore newlines until "baseurl:"
  On this blog employees of HolidayCheck share whatever they like to share.
  Mostly it will be tech stuff, though you surely find surrounding topics too.
  If you like stuff you see here, make sure to get in touch with us, we are
  always looking for pationate new colleagues!
baseurl: "" # the subpath of your site, e.g. /blog

url: "https://techblog.holidaycheck.com"

twitter_username: holidaychecklab
github_username:  holidaycheck
permalink: post/:year/:month/:day/:title
nav_list:
  Home : ['Home', '/', 'fa-home']
  Events : ['Events', '/events', 'fa-calendar']
  Jobs : ['Jobs', 'http://github.com/holidaycheck/jobs', 'fa-heart']
  Imprint : ['Imprint', 'https://www.holidaycheck.de/impressum', 'fa-envelope']
  About : ['About', '/about', 'fa-info-circle']
  Twitter : ['Twitter', 'http://twitter.com/holidaychecklab', 'fa-twitter']
  Source : ['Source', 'http://github.com/holidaycheck/tech-blog', 'fa-github']

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
